/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.AddOrderReqDetail;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class AddOrderReq  {
  
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("user_id")
  private String userId = null;
  @SerializedName("price")
  private String price = null;
  @SerializedName("paymethod")
  private String paymethod = null;
  @SerializedName("points")
  private String points = null;
  @SerializedName("tax")
  private String tax = null;
  @SerializedName("detail")
  private List<AddOrderReqDetail> detail = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPrice() {
    return price;
  }
  public void setPrice(String price) {
    this.price = price;
  }

  /**
   * 현금,카드,포인트(0,1,0)
   **/
  @ApiModelProperty(value = "현금,카드,포인트(0,1,0)")
  public String getPaymethod() {
    return paymethod;
  }
  public void setPaymethod(String paymethod) {
    this.paymethod = paymethod;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPoints() {
    return points;
  }
  public void setPoints(String points) {
    this.points = points;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTax() {
    return tax;
  }
  public void setTax(String tax) {
    this.tax = tax;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<AddOrderReqDetail> getDetail() {
    return detail;
  }
  public void setDetail(List<AddOrderReqDetail> detail) {
    this.detail = detail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddOrderReq addOrderReq = (AddOrderReq) o;
    return (storeId == null ? addOrderReq.storeId == null : storeId.equals(addOrderReq.storeId)) &&
        (userId == null ? addOrderReq.userId == null : userId.equals(addOrderReq.userId)) &&
        (price == null ? addOrderReq.price == null : price.equals(addOrderReq.price)) &&
        (paymethod == null ? addOrderReq.paymethod == null : paymethod.equals(addOrderReq.paymethod)) &&
        (points == null ? addOrderReq.points == null : points.equals(addOrderReq.points)) &&
        (tax == null ? addOrderReq.tax == null : tax.equals(addOrderReq.tax)) &&
        (detail == null ? addOrderReq.detail == null : detail.equals(addOrderReq.detail));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (userId == null ? 0: userId.hashCode());
    result = 31 * result + (price == null ? 0: price.hashCode());
    result = 31 * result + (paymethod == null ? 0: paymethod.hashCode());
    result = 31 * result + (points == null ? 0: points.hashCode());
    result = 31 * result + (tax == null ? 0: tax.hashCode());
    result = 31 * result + (detail == null ? 0: detail.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddOrderReq {\n");
    
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  paymethod: ").append(paymethod).append("\n");
    sb.append("  points: ").append(points).append("\n");
    sb.append("  tax: ").append(tax).append("\n");
    sb.append("  detail: ").append(detail).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
