/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class AddOrderReqOption  {
  
  @SerializedName("menu_id")
  private String menuId = null;
  @SerializedName("quantity")
  private String quantity = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMenuId() {
    return menuId;
  }
  public void setMenuId(String menuId) {
    this.menuId = menuId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQuantity() {
    return quantity;
  }
  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddOrderReqOption addOrderReqOption = (AddOrderReqOption) o;
    return (menuId == null ? addOrderReqOption.menuId == null : menuId.equals(addOrderReqOption.menuId)) &&
        (quantity == null ? addOrderReqOption.quantity == null : quantity.equals(addOrderReqOption.quantity));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (menuId == null ? 0: menuId.hashCode());
    result = 31 * result + (quantity == null ? 0: quantity.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddOrderReqOption {\n");
    
    sb.append("  menuId: ").append(menuId).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
