/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.MenuOptionResOptions;
import java.math.BigDecimal;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class MenuOptionResData1  {
  
  @SerializedName("menu_id")
  private String menuId = null;
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("sub_category_id")
  private String subCategoryId = null;
  @SerializedName("inventory_id")
  private String inventoryId = null;
  @SerializedName("m_item")
  private String mItem = null;
  @SerializedName("m_type")
  private Integer mType = null;
  @SerializedName("price")
  private BigDecimal price = null;
  @SerializedName("points")
  private Integer points = null;
  @SerializedName("calory")
  private Integer calory = null;
  @SerializedName("barcode")
  private String barcode = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("file_id")
  private String fileId = null;
  @SerializedName("options")
  private List<MenuOptionResOptions> options = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMenuId() {
    return menuId;
  }
  public void setMenuId(String menuId) {
    this.menuId = menuId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSubCategoryId() {
    return subCategoryId;
  }
  public void setSubCategoryId(String subCategoryId) {
    this.subCategoryId = subCategoryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInventoryId() {
    return inventoryId;
  }
  public void setInventoryId(String inventoryId) {
    this.inventoryId = inventoryId;
  }

  /**
   * 메뉴명
   **/
  @ApiModelProperty(value = "메뉴명")
  public String getMItem() {
    return mItem;
  }
  public void setMItem(String mItem) {
    this.mItem = mItem;
  }

  /**
   * 메뉴옵션 타입
   **/
  @ApiModelProperty(value = "메뉴옵션 타입")
  public Integer getMType() {
    return mType;
  }
  public void setMType(Integer mType) {
    this.mType = mType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPoints() {
    return points;
  }
  public void setPoints(Integer points) {
    this.points = points;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCalory() {
    return calory;
  }
  public void setCalory(Integer calory) {
    this.calory = calory;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBarcode() {
    return barcode;
  }
  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  /**
   * 메뉴설명
   **/
  @ApiModelProperty(value = "메뉴설명")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFileId() {
    return fileId;
  }
  public void setFileId(String fileId) {
    this.fileId = fileId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MenuOptionResOptions> getOptions() {
    return options;
  }
  public void setOptions(List<MenuOptionResOptions> options) {
    this.options = options;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MenuOptionResData1 menuOptionResData1 = (MenuOptionResData1) o;
    return (menuId == null ? menuOptionResData1.menuId == null : menuId.equals(menuOptionResData1.menuId)) &&
        (storeId == null ? menuOptionResData1.storeId == null : storeId.equals(menuOptionResData1.storeId)) &&
        (subCategoryId == null ? menuOptionResData1.subCategoryId == null : subCategoryId.equals(menuOptionResData1.subCategoryId)) &&
        (inventoryId == null ? menuOptionResData1.inventoryId == null : inventoryId.equals(menuOptionResData1.inventoryId)) &&
        (mItem == null ? menuOptionResData1.mItem == null : mItem.equals(menuOptionResData1.mItem)) &&
        (mType == null ? menuOptionResData1.mType == null : mType.equals(menuOptionResData1.mType)) &&
        (price == null ? menuOptionResData1.price == null : price.equals(menuOptionResData1.price)) &&
        (points == null ? menuOptionResData1.points == null : points.equals(menuOptionResData1.points)) &&
        (calory == null ? menuOptionResData1.calory == null : calory.equals(menuOptionResData1.calory)) &&
        (barcode == null ? menuOptionResData1.barcode == null : barcode.equals(menuOptionResData1.barcode)) &&
        (description == null ? menuOptionResData1.description == null : description.equals(menuOptionResData1.description)) &&
        (fileId == null ? menuOptionResData1.fileId == null : fileId.equals(menuOptionResData1.fileId)) &&
        (options == null ? menuOptionResData1.options == null : options.equals(menuOptionResData1.options));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (menuId == null ? 0: menuId.hashCode());
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (subCategoryId == null ? 0: subCategoryId.hashCode());
    result = 31 * result + (inventoryId == null ? 0: inventoryId.hashCode());
    result = 31 * result + (mItem == null ? 0: mItem.hashCode());
    result = 31 * result + (mType == null ? 0: mType.hashCode());
    result = 31 * result + (price == null ? 0: price.hashCode());
    result = 31 * result + (points == null ? 0: points.hashCode());
    result = 31 * result + (calory == null ? 0: calory.hashCode());
    result = 31 * result + (barcode == null ? 0: barcode.hashCode());
    result = 31 * result + (description == null ? 0: description.hashCode());
    result = 31 * result + (fileId == null ? 0: fileId.hashCode());
    result = 31 * result + (options == null ? 0: options.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MenuOptionResData1 {\n");
    
    sb.append("  menuId: ").append(menuId).append("\n");
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  subCategoryId: ").append(subCategoryId).append("\n");
    sb.append("  inventoryId: ").append(inventoryId).append("\n");
    sb.append("  mItem: ").append(mItem).append("\n");
    sb.append("  mType: ").append(mType).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  points: ").append(points).append("\n");
    sb.append("  calory: ").append(calory).append("\n");
    sb.append("  barcode: ").append(barcode).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  fileId: ").append(fileId).append("\n");
    sb.append("  options: ").append(options).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
