/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.math.BigDecimal;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class MenuResData  {
  
  @SerializedName("menu_id")
  private String menuId = null;
  @SerializedName("sub_category_id")
  private String subCategoryId = null;
  @SerializedName("m_item")
  private String mItem = null;
  @SerializedName("m_type")
  private Integer mType = null;
  @SerializedName("price")
  private BigDecimal price = null;
  @SerializedName("points")
  private Integer points = null;
  @SerializedName("calory")
  private Integer calory = null;
  @SerializedName("barcode")
  private String barcode = null;
  @SerializedName("use_YN")
  private String useYN = null;
  @SerializedName("m_regidate")
  private String mRegidate = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("file_id")
  private String fileId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMenuId() {
    return menuId;
  }
  public void setMenuId(String menuId) {
    this.menuId = menuId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSubCategoryId() {
    return subCategoryId;
  }
  public void setSubCategoryId(String subCategoryId) {
    this.subCategoryId = subCategoryId;
  }

  /**
   * 메뉴명
   **/
  @ApiModelProperty(value = "메뉴명")
  public String getMItem() {
    return mItem;
  }
  public void setMItem(String mItem) {
    this.mItem = mItem;
  }

  /**
   * 메뉴옵션 타입
   **/
  @ApiModelProperty(value = "메뉴옵션 타입")
  public Integer getMType() {
    return mType;
  }
  public void setMType(Integer mType) {
    this.mType = mType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPoints() {
    return points;
  }
  public void setPoints(Integer points) {
    this.points = points;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCalory() {
    return calory;
  }
  public void setCalory(Integer calory) {
    this.calory = calory;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBarcode() {
    return barcode;
  }
  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  /**
   * 판매여부
   **/
  @ApiModelProperty(value = "판매여부")
  public String getUseYN() {
    return useYN;
  }
  public void setUseYN(String useYN) {
    this.useYN = useYN;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMRegidate() {
    return mRegidate;
  }
  public void setMRegidate(String mRegidate) {
    this.mRegidate = mRegidate;
  }

  /**
   * 메뉴설명
   **/
  @ApiModelProperty(value = "메뉴설명")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFileId() {
    return fileId;
  }
  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MenuResData menuResData = (MenuResData) o;
    return (menuId == null ? menuResData.menuId == null : menuId.equals(menuResData.menuId)) &&
        (subCategoryId == null ? menuResData.subCategoryId == null : subCategoryId.equals(menuResData.subCategoryId)) &&
        (mItem == null ? menuResData.mItem == null : mItem.equals(menuResData.mItem)) &&
        (mType == null ? menuResData.mType == null : mType.equals(menuResData.mType)) &&
        (price == null ? menuResData.price == null : price.equals(menuResData.price)) &&
        (points == null ? menuResData.points == null : points.equals(menuResData.points)) &&
        (calory == null ? menuResData.calory == null : calory.equals(menuResData.calory)) &&
        (barcode == null ? menuResData.barcode == null : barcode.equals(menuResData.barcode)) &&
        (useYN == null ? menuResData.useYN == null : useYN.equals(menuResData.useYN)) &&
        (mRegidate == null ? menuResData.mRegidate == null : mRegidate.equals(menuResData.mRegidate)) &&
        (description == null ? menuResData.description == null : description.equals(menuResData.description)) &&
        (fileId == null ? menuResData.fileId == null : fileId.equals(menuResData.fileId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (menuId == null ? 0: menuId.hashCode());
    result = 31 * result + (subCategoryId == null ? 0: subCategoryId.hashCode());
    result = 31 * result + (mItem == null ? 0: mItem.hashCode());
    result = 31 * result + (mType == null ? 0: mType.hashCode());
    result = 31 * result + (price == null ? 0: price.hashCode());
    result = 31 * result + (points == null ? 0: points.hashCode());
    result = 31 * result + (calory == null ? 0: calory.hashCode());
    result = 31 * result + (barcode == null ? 0: barcode.hashCode());
    result = 31 * result + (useYN == null ? 0: useYN.hashCode());
    result = 31 * result + (mRegidate == null ? 0: mRegidate.hashCode());
    result = 31 * result + (description == null ? 0: description.hashCode());
    result = 31 * result + (fileId == null ? 0: fileId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MenuResData {\n");
    
    sb.append("  menuId: ").append(menuId).append("\n");
    sb.append("  subCategoryId: ").append(subCategoryId).append("\n");
    sb.append("  mItem: ").append(mItem).append("\n");
    sb.append("  mType: ").append(mType).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  points: ").append(points).append("\n");
    sb.append("  calory: ").append(calory).append("\n");
    sb.append("  barcode: ").append(barcode).append("\n");
    sb.append("  useYN: ").append(useYN).append("\n");
    sb.append("  mRegidate: ").append(mRegidate).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  fileId: ").append(fileId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
