/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.MenuOptionResData;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class MenuOptionResOptions  {
  
  @SerializedName("category_id")
  private String categoryId = null;
  @SerializedName("category_name")
  private String categoryName = null;
  @SerializedName("option_type")
  private Integer optionType = null;
  @SerializedName("data")
  private List<MenuOptionResData> data = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCategoryId() {
    return categoryId;
  }
  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCategoryName() {
    return categoryName;
  }
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOptionType() {
    return optionType;
  }
  public void setOptionType(Integer optionType) {
    this.optionType = optionType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<MenuOptionResData> getData() {
    return data;
  }
  public void setData(List<MenuOptionResData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MenuOptionResOptions menuOptionResOptions = (MenuOptionResOptions) o;
    return (categoryId == null ? menuOptionResOptions.categoryId == null : categoryId.equals(menuOptionResOptions.categoryId)) &&
        (categoryName == null ? menuOptionResOptions.categoryName == null : categoryName.equals(menuOptionResOptions.categoryName)) &&
        (optionType == null ? menuOptionResOptions.optionType == null : optionType.equals(menuOptionResOptions.optionType)) &&
        (data == null ? menuOptionResOptions.data == null : data.equals(menuOptionResOptions.data));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (categoryId == null ? 0: categoryId.hashCode());
    result = 31 * result + (categoryName == null ? 0: categoryName.hashCode());
    result = 31 * result + (optionType == null ? 0: optionType.hashCode());
    result = 31 * result + (data == null ? 0: data.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MenuOptionResOptions {\n");
    
    sb.append("  categoryId: ").append(categoryId).append("\n");
    sb.append("  categoryName: ").append(categoryName).append("\n");
    sb.append("  optionType: ").append(optionType).append("\n");
    sb.append("  data: ").append(data).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
