/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class OrderCompleteResData  {
  
  @SerializedName("order_num")
  private Integer orderNum = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOrderNum() {
    return orderNum;
  }
  public void setOrderNum(Integer orderNum) {
    this.orderNum = orderNum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderCompleteResData orderCompleteResData = (OrderCompleteResData) o;
    return (orderNum == null ? orderCompleteResData.orderNum == null : orderNum.equals(orderCompleteResData.orderNum));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (orderNum == null ? 0: orderNum.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderCompleteResData {\n");
    
    sb.append("  orderNum: ").append(orderNum).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
