/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.OrderResDetail;
import java.math.BigDecimal;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class OrderResData  {
  
  @SerializedName("order_id")
  private String orderId = null;
  @SerializedName("order_num")
  private Integer orderNum = null;
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("machine_id")
  private String machineId = null;
  @SerializedName("user_id")
  private String userId = null;
  @SerializedName("amount")
  private BigDecimal amount = null;
  @SerializedName("coupon")
  private BigDecimal coupon = null;
  @SerializedName("coupon_title")
  private String couponTitle = null;
  @SerializedName("discount")
  private BigDecimal discount = null;
  @SerializedName("discount_title")
  private String discountTitle = null;
  @SerializedName("price")
  private BigDecimal price = null;
  @SerializedName("add_points")
  private Integer addPoints = null;
  @SerializedName("order_status")
  private Integer orderStatus = null;
  @SerializedName("cook_status")
  private Integer cookStatus = null;
  @SerializedName("paymethod")
  private String paymethod = null;
  @SerializedName("user_agent")
  private Integer userAgent = null;
  @SerializedName("cash")
  private BigDecimal cash = null;
  @SerializedName("card")
  private BigDecimal card = null;
  @SerializedName("points")
  private Integer points = null;
  @SerializedName("tax")
  private BigDecimal tax = null;
  @SerializedName("package")
  private Integer _package = null;
  @SerializedName("regidate")
  private String regidate = null;
  @SerializedName("detail")
  private List<OrderResDetail> detail = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderId() {
    return orderId;
  }
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOrderNum() {
    return orderNum;
  }
  public void setOrderNum(Integer orderNum) {
    this.orderNum = orderNum;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMachineId() {
    return machineId;
  }
  public void setMachineId(String machineId) {
    this.machineId = machineId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getAmount() {
    return amount;
  }
  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getCoupon() {
    return coupon;
  }
  public void setCoupon(BigDecimal coupon) {
    this.coupon = coupon;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCouponTitle() {
    return couponTitle;
  }
  public void setCouponTitle(String couponTitle) {
    this.couponTitle = couponTitle;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getDiscount() {
    return discount;
  }
  public void setDiscount(BigDecimal discount) {
    this.discount = discount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDiscountTitle() {
    return discountTitle;
  }
  public void setDiscountTitle(String discountTitle) {
    this.discountTitle = discountTitle;
  }

  /**
   * 결제금액 = 주문총액 - 쿠폰 - 할인
   **/
  @ApiModelProperty(value = "결제금액 = 주문총액 - 쿠폰 - 할인")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getAddPoints() {
    return addPoints;
  }
  public void setAddPoints(Integer addPoints) {
    this.addPoints = addPoints;
  }

  /**
   * 주문완료, 주문취소, 환불 , null
   **/
  @ApiModelProperty(value = "주문완료, 주문취소, 환불 , null")
  public Integer getOrderStatus() {
    return orderStatus;
  }
  public void setOrderStatus(Integer orderStatus) {
    this.orderStatus = orderStatus;
  }

  /**
   * 처리중, 처리완료
   **/
  @ApiModelProperty(value = "처리중, 처리완료")
  public Integer getCookStatus() {
    return cookStatus;
  }
  public void setCookStatus(Integer cookStatus) {
    this.cookStatus = cookStatus;
  }

  /**
   * 현금,카드,포인트(1,0,0)
   **/
  @ApiModelProperty(value = "현금,카드,포인트(1,0,0)")
  public String getPaymethod() {
    return paymethod;
  }
  public void setPaymethod(String paymethod) {
    this.paymethod = paymethod;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getUserAgent() {
    return userAgent;
  }
  public void setUserAgent(Integer userAgent) {
    this.userAgent = userAgent;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getCash() {
    return cash;
  }
  public void setCash(BigDecimal cash) {
    this.cash = cash;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getCard() {
    return card;
  }
  public void setCard(BigDecimal card) {
    this.card = card;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPoints() {
    return points;
  }
  public void setPoints(Integer points) {
    this.points = points;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getTax() {
    return tax;
  }
  public void setTax(BigDecimal tax) {
    this.tax = tax;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPackage() {
    return _package;
  }
  public void setPackage(Integer _package) {
    this._package = _package;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRegidate() {
    return regidate;
  }
  public void setRegidate(String regidate) {
    this.regidate = regidate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<OrderResDetail> getDetail() {
    return detail;
  }
  public void setDetail(List<OrderResDetail> detail) {
    this.detail = detail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderResData orderResData = (OrderResData) o;
    return (orderId == null ? orderResData.orderId == null : orderId.equals(orderResData.orderId)) &&
        (orderNum == null ? orderResData.orderNum == null : orderNum.equals(orderResData.orderNum)) &&
        (storeId == null ? orderResData.storeId == null : storeId.equals(orderResData.storeId)) &&
        (machineId == null ? orderResData.machineId == null : machineId.equals(orderResData.machineId)) &&
        (userId == null ? orderResData.userId == null : userId.equals(orderResData.userId)) &&
        (amount == null ? orderResData.amount == null : amount.equals(orderResData.amount)) &&
        (coupon == null ? orderResData.coupon == null : coupon.equals(orderResData.coupon)) &&
        (couponTitle == null ? orderResData.couponTitle == null : couponTitle.equals(orderResData.couponTitle)) &&
        (discount == null ? orderResData.discount == null : discount.equals(orderResData.discount)) &&
        (discountTitle == null ? orderResData.discountTitle == null : discountTitle.equals(orderResData.discountTitle)) &&
        (price == null ? orderResData.price == null : price.equals(orderResData.price)) &&
        (addPoints == null ? orderResData.addPoints == null : addPoints.equals(orderResData.addPoints)) &&
        (orderStatus == null ? orderResData.orderStatus == null : orderStatus.equals(orderResData.orderStatus)) &&
        (cookStatus == null ? orderResData.cookStatus == null : cookStatus.equals(orderResData.cookStatus)) &&
        (paymethod == null ? orderResData.paymethod == null : paymethod.equals(orderResData.paymethod)) &&
        (userAgent == null ? orderResData.userAgent == null : userAgent.equals(orderResData.userAgent)) &&
        (cash == null ? orderResData.cash == null : cash.equals(orderResData.cash)) &&
        (card == null ? orderResData.card == null : card.equals(orderResData.card)) &&
        (points == null ? orderResData.points == null : points.equals(orderResData.points)) &&
        (tax == null ? orderResData.tax == null : tax.equals(orderResData.tax)) &&
        (_package == null ? orderResData._package == null : _package.equals(orderResData._package)) &&
        (regidate == null ? orderResData.regidate == null : regidate.equals(orderResData.regidate)) &&
        (detail == null ? orderResData.detail == null : detail.equals(orderResData.detail));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (orderId == null ? 0: orderId.hashCode());
    result = 31 * result + (orderNum == null ? 0: orderNum.hashCode());
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (machineId == null ? 0: machineId.hashCode());
    result = 31 * result + (userId == null ? 0: userId.hashCode());
    result = 31 * result + (amount == null ? 0: amount.hashCode());
    result = 31 * result + (coupon == null ? 0: coupon.hashCode());
    result = 31 * result + (couponTitle == null ? 0: couponTitle.hashCode());
    result = 31 * result + (discount == null ? 0: discount.hashCode());
    result = 31 * result + (discountTitle == null ? 0: discountTitle.hashCode());
    result = 31 * result + (price == null ? 0: price.hashCode());
    result = 31 * result + (addPoints == null ? 0: addPoints.hashCode());
    result = 31 * result + (orderStatus == null ? 0: orderStatus.hashCode());
    result = 31 * result + (cookStatus == null ? 0: cookStatus.hashCode());
    result = 31 * result + (paymethod == null ? 0: paymethod.hashCode());
    result = 31 * result + (userAgent == null ? 0: userAgent.hashCode());
    result = 31 * result + (cash == null ? 0: cash.hashCode());
    result = 31 * result + (card == null ? 0: card.hashCode());
    result = 31 * result + (points == null ? 0: points.hashCode());
    result = 31 * result + (tax == null ? 0: tax.hashCode());
    result = 31 * result + (_package == null ? 0: _package.hashCode());
    result = 31 * result + (regidate == null ? 0: regidate.hashCode());
    result = 31 * result + (detail == null ? 0: detail.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderResData {\n");
    
    sb.append("  orderId: ").append(orderId).append("\n");
    sb.append("  orderNum: ").append(orderNum).append("\n");
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  machineId: ").append(machineId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  coupon: ").append(coupon).append("\n");
    sb.append("  couponTitle: ").append(couponTitle).append("\n");
    sb.append("  discount: ").append(discount).append("\n");
    sb.append("  discountTitle: ").append(discountTitle).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  addPoints: ").append(addPoints).append("\n");
    sb.append("  orderStatus: ").append(orderStatus).append("\n");
    sb.append("  cookStatus: ").append(cookStatus).append("\n");
    sb.append("  paymethod: ").append(paymethod).append("\n");
    sb.append("  userAgent: ").append(userAgent).append("\n");
    sb.append("  cash: ").append(cash).append("\n");
    sb.append("  card: ").append(card).append("\n");
    sb.append("  points: ").append(points).append("\n");
    sb.append("  tax: ").append(tax).append("\n");
    sb.append("  _package: ").append(_package).append("\n");
    sb.append("  regidate: ").append(regidate).append("\n");
    sb.append("  detail: ").append(detail).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
