/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.math.BigDecimal;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class OrderResOption  {
  
  @SerializedName("order_option_id")
  private String orderOptionId = null;
  @SerializedName("option_menu_id")
  private String optionMenuId = null;
  @SerializedName("option_quantity")
  private Integer optionQuantity = null;
  @SerializedName("option_file_id")
  private String optionFileId = null;
  @SerializedName("option_menu_name")
  private String optionMenuName = null;
  @SerializedName("option_price")
  private BigDecimal optionPrice = null;
  @SerializedName("option_calory")
  private Integer optionCalory = null;
  @SerializedName("option_points")
  private Integer optionPoints = null;
  @SerializedName("option_op")
  private Integer optionOp = null;
  @SerializedName("option_description")
  private String optionDescription = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderOptionId() {
    return orderOptionId;
  }
  public void setOrderOptionId(String orderOptionId) {
    this.orderOptionId = orderOptionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOptionMenuId() {
    return optionMenuId;
  }
  public void setOptionMenuId(String optionMenuId) {
    this.optionMenuId = optionMenuId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOptionQuantity() {
    return optionQuantity;
  }
  public void setOptionQuantity(Integer optionQuantity) {
    this.optionQuantity = optionQuantity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOptionFileId() {
    return optionFileId;
  }
  public void setOptionFileId(String optionFileId) {
    this.optionFileId = optionFileId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOptionMenuName() {
    return optionMenuName;
  }
  public void setOptionMenuName(String optionMenuName) {
    this.optionMenuName = optionMenuName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getOptionPrice() {
    return optionPrice;
  }
  public void setOptionPrice(BigDecimal optionPrice) {
    this.optionPrice = optionPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOptionCalory() {
    return optionCalory;
  }
  public void setOptionCalory(Integer optionCalory) {
    this.optionCalory = optionCalory;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOptionPoints() {
    return optionPoints;
  }
  public void setOptionPoints(Integer optionPoints) {
    this.optionPoints = optionPoints;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOptionOp() {
    return optionOp;
  }
  public void setOptionOp(Integer optionOp) {
    this.optionOp = optionOp;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOptionDescription() {
    return optionDescription;
  }
  public void setOptionDescription(String optionDescription) {
    this.optionDescription = optionDescription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderResOption orderResOption = (OrderResOption) o;
    return (orderOptionId == null ? orderResOption.orderOptionId == null : orderOptionId.equals(orderResOption.orderOptionId)) &&
        (optionMenuId == null ? orderResOption.optionMenuId == null : optionMenuId.equals(orderResOption.optionMenuId)) &&
        (optionQuantity == null ? orderResOption.optionQuantity == null : optionQuantity.equals(orderResOption.optionQuantity)) &&
        (optionFileId == null ? orderResOption.optionFileId == null : optionFileId.equals(orderResOption.optionFileId)) &&
        (optionMenuName == null ? orderResOption.optionMenuName == null : optionMenuName.equals(orderResOption.optionMenuName)) &&
        (optionPrice == null ? orderResOption.optionPrice == null : optionPrice.equals(orderResOption.optionPrice)) &&
        (optionCalory == null ? orderResOption.optionCalory == null : optionCalory.equals(orderResOption.optionCalory)) &&
        (optionPoints == null ? orderResOption.optionPoints == null : optionPoints.equals(orderResOption.optionPoints)) &&
        (optionOp == null ? orderResOption.optionOp == null : optionOp.equals(orderResOption.optionOp)) &&
        (optionDescription == null ? orderResOption.optionDescription == null : optionDescription.equals(orderResOption.optionDescription));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (orderOptionId == null ? 0: orderOptionId.hashCode());
    result = 31 * result + (optionMenuId == null ? 0: optionMenuId.hashCode());
    result = 31 * result + (optionQuantity == null ? 0: optionQuantity.hashCode());
    result = 31 * result + (optionFileId == null ? 0: optionFileId.hashCode());
    result = 31 * result + (optionMenuName == null ? 0: optionMenuName.hashCode());
    result = 31 * result + (optionPrice == null ? 0: optionPrice.hashCode());
    result = 31 * result + (optionCalory == null ? 0: optionCalory.hashCode());
    result = 31 * result + (optionPoints == null ? 0: optionPoints.hashCode());
    result = 31 * result + (optionOp == null ? 0: optionOp.hashCode());
    result = 31 * result + (optionDescription == null ? 0: optionDescription.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderResOption {\n");
    
    sb.append("  orderOptionId: ").append(orderOptionId).append("\n");
    sb.append("  optionMenuId: ").append(optionMenuId).append("\n");
    sb.append("  optionQuantity: ").append(optionQuantity).append("\n");
    sb.append("  optionFileId: ").append(optionFileId).append("\n");
    sb.append("  optionMenuName: ").append(optionMenuName).append("\n");
    sb.append("  optionPrice: ").append(optionPrice).append("\n");
    sb.append("  optionCalory: ").append(optionCalory).append("\n");
    sb.append("  optionPoints: ").append(optionPoints).append("\n");
    sb.append("  optionOp: ").append(optionOp).append("\n");
    sb.append("  optionDescription: ").append(optionDescription).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
