/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.math.BigDecimal;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class StoresResData  {
  
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("user_id")
  private String userId = null;
  @SerializedName("store")
  private String store = null;
  @SerializedName("u_points")
  private Integer uPoints = null;
  @SerializedName("u_status")
  private Integer uStatus = null;
  @SerializedName("u_level")
  private String uLevel = null;
  @SerializedName("s_address")
  private String sAddress = null;
  @SerializedName("s_logo")
  private String sLogo = null;
  @SerializedName("s_tax")
  private BigDecimal sTax = null;
  @SerializedName("s_phone")
  private String sPhone = null;

  /**
   * 매장번호
   **/
  @ApiModelProperty(value = "매장번호")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * 회사명
   **/
  @ApiModelProperty(value = "회사명")
  public String getStore() {
    return store;
  }
  public void setStore(String store) {
    this.store = store;
  }

  /**
   * 스토어별 point
   **/
  @ApiModelProperty(value = "스토어별 point")
  public Integer getUPoints() {
    return uPoints;
  }
  public void setUPoints(Integer uPoints) {
    this.uPoints = uPoints;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getUStatus() {
    return uStatus;
  }
  public void setUStatus(Integer uStatus) {
    this.uStatus = uStatus;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getULevel() {
    return uLevel;
  }
  public void setULevel(String uLevel) {
    this.uLevel = uLevel;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSAddress() {
    return sAddress;
  }
  public void setSAddress(String sAddress) {
    this.sAddress = sAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSLogo() {
    return sLogo;
  }
  public void setSLogo(String sLogo) {
    this.sLogo = sLogo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getSTax() {
    return sTax;
  }
  public void setSTax(BigDecimal sTax) {
    this.sTax = sTax;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSPhone() {
    return sPhone;
  }
  public void setSPhone(String sPhone) {
    this.sPhone = sPhone;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoresResData storesResData = (StoresResData) o;
    return (storeId == null ? storesResData.storeId == null : storeId.equals(storesResData.storeId)) &&
        (userId == null ? storesResData.userId == null : userId.equals(storesResData.userId)) &&
        (store == null ? storesResData.store == null : store.equals(storesResData.store)) &&
        (uPoints == null ? storesResData.uPoints == null : uPoints.equals(storesResData.uPoints)) &&
        (uStatus == null ? storesResData.uStatus == null : uStatus.equals(storesResData.uStatus)) &&
        (uLevel == null ? storesResData.uLevel == null : uLevel.equals(storesResData.uLevel)) &&
        (sAddress == null ? storesResData.sAddress == null : sAddress.equals(storesResData.sAddress)) &&
        (sLogo == null ? storesResData.sLogo == null : sLogo.equals(storesResData.sLogo)) &&
        (sTax == null ? storesResData.sTax == null : sTax.equals(storesResData.sTax)) &&
        (sPhone == null ? storesResData.sPhone == null : sPhone.equals(storesResData.sPhone));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (userId == null ? 0: userId.hashCode());
    result = 31 * result + (store == null ? 0: store.hashCode());
    result = 31 * result + (uPoints == null ? 0: uPoints.hashCode());
    result = 31 * result + (uStatus == null ? 0: uStatus.hashCode());
    result = 31 * result + (uLevel == null ? 0: uLevel.hashCode());
    result = 31 * result + (sAddress == null ? 0: sAddress.hashCode());
    result = 31 * result + (sLogo == null ? 0: sLogo.hashCode());
    result = 31 * result + (sTax == null ? 0: sTax.hashCode());
    result = 31 * result + (sPhone == null ? 0: sPhone.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoresResData {\n");
    
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  store: ").append(store).append("\n");
    sb.append("  uPoints: ").append(uPoints).append("\n");
    sb.append("  uStatus: ").append(uStatus).append("\n");
    sb.append("  uLevel: ").append(uLevel).append("\n");
    sb.append("  sAddress: ").append(sAddress).append("\n");
    sb.append("  sLogo: ").append(sLogo).append("\n");
    sb.append("  sTax: ").append(sTax).append("\n");
    sb.append("  sPhone: ").append(sPhone).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
