/**
 * Kiosk API
 * 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class SubcategoryResData  {
  
  @SerializedName("sub_category_id")
  private String subCategoryId = null;
  @SerializedName("sub_category_name")
  private String subCategoryName = null;
  @SerializedName("file_id")
  private String fileId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSubCategoryId() {
    return subCategoryId;
  }
  public void setSubCategoryId(String subCategoryId) {
    this.subCategoryId = subCategoryId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSubCategoryName() {
    return subCategoryName;
  }
  public void setSubCategoryName(String subCategoryName) {
    this.subCategoryName = subCategoryName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFileId() {
    return fileId;
  }
  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubcategoryResData subcategoryResData = (SubcategoryResData) o;
    return (subCategoryId == null ? subcategoryResData.subCategoryId == null : subCategoryId.equals(subcategoryResData.subCategoryId)) &&
        (subCategoryName == null ? subcategoryResData.subCategoryName == null : subCategoryName.equals(subcategoryResData.subCategoryName)) &&
        (fileId == null ? subcategoryResData.fileId == null : fileId.equals(subcategoryResData.fileId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (subCategoryId == null ? 0: subCategoryId.hashCode());
    result = 31 * result + (subCategoryName == null ? 0: subCategoryName.hashCode());
    result = 31 * result + (fileId == null ? 0: fileId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubcategoryResData {\n");
    
    sb.append("  subCategoryId: ").append(subCategoryId).append("\n");
    sb.append("  subCategoryName: ").append(subCategoryName).append("\n");
    sb.append("  fileId: ").append(fileId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
